name: CI TEST                        # workflow 이름
on:
  push:                             # event trigger on push
    branches: 
      - master
      - dev

jobs:
  build:                             # job id
    name: Build Test                 # job 이름
    runs-on: ubuntu-latest           # 가상 환경
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for Yarn Pkg
      uses: funkyremi/yarn-github-action@1.0.0
    - name: Run Node server
      run: sudo yarn && yarn test
    - name: Build docker image    
      run: docker build -t kygha7205/shuttle_api:latest .
    - name: Test image
      run: docker run -d -p 8080:8080 --name shuttle-api kygha7205/shuttle_api:latest
